### ISSUE TITLE
User Story: Single prompt view with text editor

### ISSUE THREAD

**Issue by lmariereese** [lmariereese/story-prompts#25]
As a user, I want to view a single saved prompt with a text editor so that I can start writing. 

- [x] SinglePromptView component
- [x] Research text editor frameworks
- [x] Install draft.js
- [x] Style draft editor
- [x] Model for content #33 
- [x] API routes for content #32 
- [x] Redux for content #34
