### ISSUE TITLE
User Story: Generate a short story prompt

### ISSUE THREAD

**Issue by lmariereese** [lmariereese/story-prompts#5]
As a visitor or logged in user, I want to click a button, so that I can see a unique short story prompt. 

- [x] API routes to get story elements #11 
- [x] Create reducers for the story elements #12
- [x] Create component to generate and display prompt #13
- [x] display correct article #14
