### ISSUE TITLE
User Story: Share a prompt

### ISSUE THREAD

**Issue by lmariereese** [lmariereese/story-prompts#56]
As a user, I want to click a button to create a link to the current prompt I'm viewing, so that I can share it with others. 

- [x] Add url token field to prompt table #57
- [x] New API route to POST prompt with unique url token and userId null #58
- [x] Actions/thunks for sharing a prompt & storing urlToken in redux state #60
- [x] Component to display URL to copy
- [x] Don't save twice if user clicks on share twice for same prompt #64
- [x] Don't save again if user is viewing a shared prompt via /prompts/urlToken route
- [x] Automatically copy link to clipboard  #63
